export const STRINGS = {
  app: {
    name: 'NivassHub',
    tagline: 'Smart Gated Community Management',
  },

  auth: {
    login: 'Login',
    logout: 'Logout',
    email: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Sign In',
    loginSubtitle: 'Sign in to your NivassHub account',
    invalidCredentials: 'Invalid email or password. Please try again.',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
  },

  home: {
    title: 'Dashboard',
    welcome: 'Welcome back,',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    societyOverview: 'Society Overview',
    todayVisitors: "Today's Visitors",
    openComplaints: 'Open Complaints',
    pendingPayments: 'Pending Payments',
    activeNotices: 'Active Notices',
  },

  visitors: {
    title: 'Visitors',
    addVisitor: 'Add Visitor',
    currentlyInside: 'Currently Inside',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    purpose: 'Purpose of Visit',
    noVisitors: 'No visitors today',
    noVisitorsSubtext: 'All visitor entries will appear here.',
  },

  complaints: {
    title: 'Complaints',
    newComplaint: 'New Complaint',
    status_open: 'Open',
    status_in_progress: 'In Progress',
    status_resolved: 'Resolved',
    status_under_review: 'Under Review',
    priority_low: 'Low',
    priority_medium: 'Medium',
    priority_high: 'High',
    priority_critical: 'Critical',
    noComplaints: 'No complaints found',
    noComplaintsSubtext: 'Your community complaints will appear here.',
  },

  notices: {
    title: 'Notices',
    pinned: 'Pinned',
    noNotices: 'No notices',
    noNoticesSubtext: 'Community notices and announcements will appear here.',
  },

  payments: {
    title: 'Payments',
    makePayment: 'Make Payment',
    status_paid: 'Paid',
    status_pending: 'Pending',
    status_overdue: 'Overdue',
    amountDue: 'Amount Due',
    amountPaid: 'Amount Paid',
    noPayments: 'No payment records',
    noPaymentsSubtext: 'Your payment history will appear here.',
  },

  profile: {
    title: 'My Profile',
    flat: 'Flat',
    block: 'Block',
    phone: 'Phone',
    email: 'Email',
    role: 'Role',
    familyMembers: 'Family Members',
    vehicle: 'Vehicle Number',
    editProfile: 'Edit Profile',
    memberSince: 'Member Since',
  },

  common: {
    loading: 'Loading...',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    seeAll: 'See All',
    noData: 'No data available',
    error: 'Something went wrong',
    success: 'Success',
  },
};
